title: "AAC for All"
description: "Free, open-source AAC tools and pre-configured tablets for families"
url: "https://helloluna.github.io"
baseurl: "/aacforall"

remote_theme: "mmistakes/minimal-mistakes@4.27.1"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author: Hanyu
      comments: false
sass:
  sass_dir: _sass
  style: compressed

markdown: kramdown
kramdown:
  input: GFM
