title: AAC for All
email: helloluna520@gmail.com
description: "Free AAC apps & pre-configured tablets for non-speaking children"
baseurl: "/aacforall"        # 若用 USERNAME.github.io/aacforall，则填 "/aacforall"
url: "https://aacforall.org"
theme: minimal-mistakes-jekyll
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-feed
  - jekyll-seo-tag
markdown: kramdown
kramdown:
  input: GFM
